INSERT INTO users (surname, first_name, fathers_name, departament, eventsid, is_authorized, login, mail, password, role, user_group)
VALUES ('Admin', 'Admin', 'Admin', 'admistration', '', false, 'admin', 'admin@uni-dubna.ru',  'admin', 'admin', ''),
    ('User1', 'User1', 'User1', 'ИСАУ', '', false, 'user1', 'user1@uni-dubna.ru',  'user1', 'user', ''),
    ('User2', 'User2', 'User2', 'ФСГН', '', false, 'user2', 'user2@uni-dubna.ru',  'user2', 'user', ''),
    ('User3', 'User3', 'User3', 'ИФИ', '', false, 'user3', 'user3@uni-dubna.ru',  'user3', 'user', ''),
    ('User4', 'User4', 'User4', 'ФЕИН', '', false, 'user4', 'user4@uni-dubna.ru',  'user4', 'user', ''),
    ('Student1', 'Student1', 'Student1', 'ПРИНЖ', '', false, 'student1', 'student1@uni-dubna.ru',  'student1', 'student', '4254'),
    ('Student2', 'Student2', 'Student2', 'ИВТ-ТРПО', '', false, 'student2', 'student2@uni-dubna.ru',  'student2', 'student', '4011'),
    ('Student3', 'Student3', 'Student3', 'ФИИТ', '', false, 'student3', 'student3@uni-dubna.ru',  'student3', 'student', '4221'),
    ('Student4', 'Student4', 'Student4', 'СР', '', false, 'student4', 'student4@uni-dubna.ru',  'student4', 'student', '4051'),
    ('Student5', 'Student5', 'Student5', 'ГП', '', false, 'student5', 'student5@uni-dubna.ru',  'student5', 'student', '4061'),
    ('Student6', 'Student6', 'Student6', 'УП', '', false, 'student6', 'student6@uni-dubna.ru',  'student6', 'student', '4062'),
    ('Student7', 'Student7', 'Student7', 'УП', '', false, 'student7', 'student7@uni-dubna.ru',  'student7', 'student', '4062 '),
    ('Student8', 'Student8', 'Student8', 'ЯФТ-ЭФУ', '', false, 'student8', 'student8@uni-dubna.ru',  'student8', 'student', '4122'),
    ('Student9', 'Student9', 'Student9', 'Авиастроение', '', false, 'student9', 'student9@uni-dubna.ru',  'student9', 'student', '4261 '),
    ('Student10', 'Student10', 'Student10', 'Электроэнергетика', '', false, 'student10', 'student10@uni-dubna.ru',  'student10', 'student', '4081');
